[package]
name = "aria"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.13.1"
log = "0.4.22"
simple_logger = "5.0.0"

aria-core = { path = "../aria-core" }
aria-utils = { path = "../aria-utils" }
